spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
logging:
  file:
    path: ./logs/smarter-store-local/
  level:
    org.hibernate.orm.jdbc.bind: TRACE

jwt:
  secret: ${JWT_SECRET_LOCAL} # A simpler secret for local development
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

app:
  frontend-url: http://localhost:3000
