spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  logging:
    file:
      path: ./logs/smarter-store-local/ # Local logs can be relative to project root
jwt:
  secret: ${JWT_SECRET_LOCAL} # A simpler secret for local development
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

app:
  frontend-url: http://localhost:3000
