spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  logging:
    file:
      path: /home/cic/logs/smarter-store/

jwt:
  secret: ${JWT_SECRET_PROD} # Production secret, should be from env variable

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

app:
  frontend-url: ${FRONTEND_URL:https://ticket.devhong.cc}

slack: # prod에만 설정
  webhook-url: ${SLACK_WEBHOOK_URL:http://localhost}