spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
  logging:
    file:
      path: /home/cic/logs/smarter-store/

jwt:
  secret: ${JWT_SECRET_PROD} # Production secret, should be from env variable

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000, http://localhost:5173, http://127.0.0.1:3000, http://127.0.0.1:5173}
