spring:
  application:
    name: smarter-store-api
  profiles:
    active: local # Default to local profile
  jpa:
    hibernate:
      ddl-auto: none # Flyway를 사용하므로 none으로 설정
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT 설정 (secret은 프로파일로 이동)
jwt:
  access-token-validity-in-seconds: 3600 # 1시간