spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
logging:
  file:
    path: ./logs/smarter-store-local/
  level:
    org.hibernate.orm.jdbc.bind: TRACE

jwt:
  secret: ${JWT_SECRET_LOCAL}

encryption:
  secret-key: ${ENCRYPTION_SECRET_LOCAL}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

app:
  frontend-url: http://localhost:3000
  frontend:
    revalidate-url: http://localhost:3000/api/revalidate
    revalidate-token: local-revalidate-secret-token
